# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Update Website CI

on:
  push:
    branches: [ "main" ]
  repository_dispatch:
    types: [update-website]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: 'website'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run prod

  build-node:
    runs-on: ubuntu-latest

    steps :
      - uses: actions/checkout@v4 
        with:
          repository: 'warthog-network/Warthog'
          ref: 'network_refactor'
          path: 'Warthog'
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name : Meson Test
        run : DOCKER_BUILDKIT=1 docker build . --file dockerfiles/run_tests --progress plain

      - name: Docker Build
        run: DOCKER_BUILDKIT=1 docker build . -f dockerfiles/build_emscripten --output build
  
  merge-website-and-node:
  needs : [build, build-node]
  runs-on: ubuntu-latest

  - name: Move node artifacts to website
  - run : cp -r Warthog/build/wasm/* website/out

    